#Pantallas
PANTALLA_PRINCIPAL = 0
PANTALLA_PAUSA = 1
PANTALLA_GAMEOVER = 2
PANTALLA_VICTORIA = 3
PANTALLA_CUTSCENE = 4
    
NUM_FASE_INICIAL = 1    
NUM_FASE_FINAL = 3 #Sin usar de momento

#Colores
BLANCO = (255, 255, 255)
NEGRO = (0,0,0)

TEXTO = 1
TITULO = 2

ANCHO_PANTALLA = 800
ALTO_PANTALLA =  600

